### PR TITLE
changes sizes to acommodate path

### PR DESCRIPTION
**Pull request by andresgalante**
@bleathem Can we make the "entry" space to the AMQ narrow?
https://dl.dropboxusercontent.com/u/4371641/broker.png

### CODE REVIEW

**Comment by bleathem** [comment]
yep, that is completely configurable.

**Comment by andresgalante** [comment]
@bleathem how about this?

**Comment by andresgalante** [comment]
@bleathem take a look at this

**Comment by andresgalante** [comment]
@bleathem Can we narrow this also? https://dl.dropboxusercontent.com/u/4371641/path.png

**Pull request merged**
